[package]
name = "rill-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
afl = "0.18.2"
rill-syntax = { path = "../crates/rill-syntax" }
rill-runtime = { path = "../crates/rill-runtime" }

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }

[lints.rust]
unfulfilled_lint_expectations = "deny"
