#!/usr/bin/env python3
"""Generate deterministic C tables from hash-verified Unicode inputs."""

import argparse
import hashlib
import json
from collections.abc import Iterable, Iterator, Mapping
from itertools import chain
from pathlib import Path
from typing import TypedDict

type Range = tuple[int, int, str]
type Property = tuple[int, int, tuple[str, ...]]


class Input(TypedDict):
    file: str
    sha256: str


class Manifest(TypedDict):
    version: str
    inputs: list[Input]


GRAPHEME_NAMES = (
    "Other",
    "CR",
    "LF",
    "Control",
    "Extend",
    "ZWJ",
    "RI",
    "Prepend",
    "SpacingMark",
    "L",
    "V",
    "T",
    "LV",
    "LVT",
)


def properties(text: str) -> Iterator[Property]:
    """Parse UCD property records, excluding comments and blank lines."""
    for line in text.splitlines():
        fields = tuple(map(str.strip, line.partition("#")[0].split(";")))
        if len(fields) >= 2 and fields[0]:
            bounds = fields[0].split("..")
            yield int(bounds[0], 16), int(bounds[-1], 16), fields[1:]


def selected(text: str, names: set[str]) -> Iterator[Range]:
    return (
        (first, last, "1")
        for first, last, fields in properties(text)
        if fields[0] in names
    )


def combining(text: str) -> Iterator[Range]:
    for fields in (line.split(";") for line in text.splitlines()):
        if fields[2] in {"Mn", "Me", "Mc", "Cc", "Cf"}:
            scalar = int(fields[0], 16)
            yield scalar, scalar, "1"


def coalesced(ranges: Iterable[Range]) -> Iterator[Range]:
    """Normalize code-point ranges for binary search; reject conflicting overlaps."""
    current: Range | None = None
    for first, last, prop in sorted(ranges):
        if not 0 <= first <= last <= 0x10FFFF:
            raise ValueError(f"Invalid Unicode range: {first:#x}..{last:#x}")
        if current is None:
            current = first, last, prop
            continue
        start, end, previous = current
        if first <= end and prop != previous:
            raise ValueError(f"Conflicting Unicode properties at {first:#x}")
        if first <= end + 1 and prop == previous:
            current = start, max(end, last), prop
        else:
            yield current
            current = first, last, prop
    if current is not None:
        yield current


def table(name: str, ranges: Iterable[Range]) -> Iterator[str]:
    yield f"static const Range {name}[] = {{"
    yield from (
        f"  {{0x{first:x}, 0x{last:x}, {prop}}},"
        for first, last, prop in coalesced(ranges)
    )
    yield "};"


def generate(version: str, inputs: Mapping[str, str]) -> str:
    """Render verified property data as C enums and compact range tables."""
    core = inputs["DerivedCoreProperties.txt"]
    emoji = inputs["emoji-data.txt"]
    tables = (
        (
            "gcb",
            (
                (
                    first,
                    last,
                    "G_" + ("RI" if fields[0] == "Regional_Indicator" else fields[0]),
                )
                for first, last, fields in properties(
                    inputs["GraphemeBreakProperty.txt"]
                )
            ),
        ),
        (
            "incb",
            (
                (first, last, "I_" + fields[1])
                for first, last, fields in properties(core)
                if fields[0] == "InCB"
            ),
        ),
        ("pictographic", selected(emoji, {"Extended_Pictographic"})),
        ("emoji_presentation", selected(emoji, {"Emoji_Presentation"})),
        ("wide", selected(inputs["EastAsianWidth.txt"], {"W", "F"})),
        (
            "invisible",
            chain(
                selected(core, {"Default_Ignorable_Code_Point"}),
                combining(inputs["UnicodeData.txt"]),
            ),
        ),
    )
    header = (
        f"// Generated by tools/unicode.py; Unicode {version}. Do not edit.",
        "enum { " + ", ".join(f"G_{name}" for name in GRAPHEME_NAMES) + " };",
        "enum { I_None, I_Consonant, I_Extend, I_Linker };",
    )
    body = chain.from_iterable(table(name, ranges) for name, ranges in tables)
    return "\n".join(chain(header, body)) + "\n"


def verified_inputs(directory: Path, manifest: Manifest) -> dict[str, str]:
    """Read and verify pinned bytes before any property transformation."""
    inputs = {}
    for item in manifest["inputs"]:
        data = (directory / item["file"]).read_bytes()
        if hashlib.sha256(data).hexdigest() != item["sha256"]:
            raise ValueError(f"Unicode input hash mismatch: {item['file']}")
        inputs[item["file"]] = data.decode("utf-8")
    return inputs


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check generated tables without changing files",
    )
    args = parser.parse_args()
    root = Path(__file__).parent.parent
    directory = root / "data/unicode"
    manifest = json.loads((directory / "manifest.json").read_text(encoding="utf-8"))
    result = generate(manifest["version"], verified_inputs(directory, manifest)).encode(
        "utf-8"
    )
    target = root / "src/text/unicode_tables.inc"
    if args.check:
        if target.read_bytes() != result:
            raise SystemExit(
                "Unicode tables are out of date; run 'python3 tools/unicode.py'"
            )
    else:
        target.write_bytes(result)


if __name__ == "__main__":
    main()
