#!/usr/bin/env python3
"""Generate deterministic C tables from hash-verified Unicode inputs."""

import argparse
import hashlib
import json
from collections.abc import Iterable, Iterator
from itertools import chain
from pathlib import Path
from typing import TypedDict

type Range = tuple[int, int, str]
type Property = tuple[int, int, tuple[str, ...]]


class Input(TypedDict):
    file: str
    sha256: str


class Manifest(TypedDict):
    version: str
    inputs: list[Input]


GRAPHEME_NAMES = (
    "Other",
    "CR",
    "LF",
    "Control",
    "Extend",
    "ZWJ",
    "RI",
    "Prepend",
    "SpacingMark",
    "L",
    "V",
    "T",
    "LV",
    "LVT",
)


def properties(text: str) -> Iterator[Property]:
    """Parse UCD property records, excluding comments and blank lines."""
    for line in text.splitlines():
        fields = tuple(map(str.strip, line.partition("#")[0].split(";")))
        if len(fields) >= 2 and fields[0]:
            bounds = fields[0].split("..")
            yield int(bounds[0], 16), int(bounds[-1], 16), fields[1:]


def selected(text: str, names: set[str]) -> Iterator[Range]:
    return (
        (first, last, "1")
        for first, last, fields in properties(text)
        if fields[0] in names
    )


def combining(text: str) -> Iterator[Range]:
    for fields in (line.split(";") for line in text.splitlines()):
        if fields[2] in {"Mn", "Me", "Mc", "Cc", "Cf"}:
            scalar = int(fields[0], 16)
            yield scalar, scalar, "1"


def coalesced(ranges: Iterable[Range]) -> Iterator[Range]:
    """Sort ranges and merge overlapping or adjacent ranges with equal properties."""
    ordered = iter(sorted(ranges))
    current = next(ordered, None)
    if current is None:
        return
    for first, last, prop in ordered:
        start, end, previous = current
        if first <= end + 1 and prop == previous:
            current = start, max(end, last), prop
        else:
            yield current
            current = first, last, prop
    yield current


def table(name: str, ranges: Iterable[Range]) -> Iterator[str]:
    yield f"static const Range {name}[] = {{"
    yield from (
        f"  {{0x{first:x}, 0x{last:x}, {prop}}},"
        for first, last, prop in coalesced(ranges)
    )
    yield "};"


def generate(version: str, inputs: dict[str, str]) -> str:
    """Render verified property data as C enums and compact range tables."""
    core = inputs["DerivedCoreProperties.txt"]
    emoji = inputs["emoji-data.txt"]
    tables = (
        (
            "gcb",
            (
                (
                    first,
                    last,
                    "G_" + ("RI" if fields[0] == "Regional_Indicator" else fields[0]),
                )
                for first, last, fields in properties(
                    inputs["GraphemeBreakProperty.txt"]
                )
            ),
        ),
        (
            "incb",
            (
                (first, last, "I_" + fields[1])
                for first, last, fields in properties(core)
                if fields[0] == "InCB"
            ),
        ),
        ("pictographic", selected(emoji, {"Extended_Pictographic"})),
        ("emoji_presentation", selected(emoji, {"Emoji_Presentation"})),
        ("wide", selected(inputs["EastAsianWidth.txt"], {"W", "F"})),
        (
            "invisible",
            chain(
                selected(core, {"Default_Ignorable_Code_Point"}),
                combining(inputs["UnicodeData.txt"]),
            ),
        ),
    )
    header = (
        f"// Generated by tools/unicode.py; Unicode {version}. Do not edit.",
        "enum { " + ", ".join(f"G_{name}" for name in GRAPHEME_NAMES) + " };",
        "enum { I_None, I_Consonant, I_Extend, I_Linker };",
    )
    return "\n".join(chain(header, *(table(*item) for item in tables))) + "\n"


def verified_inputs(directory: Path, manifest: Manifest) -> dict[str, str]:
    def read(item: Input) -> tuple[str, str]:
        data = (directory / item["file"]).read_bytes()
        if hashlib.sha256(data).hexdigest() != item["sha256"]:
            raise ValueError(f"Unicode input hash mismatch: {item['file']}")
        return item["file"], data.decode("utf-8")

    return dict(map(read, manifest["inputs"]))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify without rewriting")
    args = parser.parse_args()
    root = Path(__file__).parent.parent
    directory = root / "data/unicode"
    manifest = json.loads((directory / "manifest.json").read_text(encoding="utf-8"))
    result = generate(manifest["version"], verified_inputs(directory, manifest))
    target = root / "src/text/unicode_tables.inc"
    if args.check:
        if target.read_text(encoding="utf-8") != result:
            raise SystemExit("Unicode tables differ; run tools/unicode.py")
    else:
        target.write_text(result, encoding="utf-8")


if __name__ == "__main__":
    main()
